/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_ffmpegtest_NullRoutinePlayer */

#ifndef _Included_com_example_ffmpegtest_NullRoutinePlayer
#define _Included_com_example_ffmpegtest_NullRoutinePlayer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_ffmpegtest_NullRoutinePlayer
 * Method:    init
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_example_ffmpegtest_NullRoutinePlayer_init
        (JNIEnv *, jobject, jstring, jobject);

JNIEXPORT void JNICALL Java_com_example_ffmpegtest_NullRoutinePlayer_sound
        (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
