/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "../../../../../../androidsdk/ndk/20.0.5594570/toolchains/llvm/prebuilt/windows-x86_64/sysroot/usr/include/jni.h"
/* Header for class com_example_ffmpegtest_VideoUtils */

#ifndef _Included_com_example_ffmpegtest_VideoUtils
#define _Included_com_example_ffmpegtest_VideoUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_ffmpegtest_VideoUtils
 * Method:    decode
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
extern "C" JNIEXPORT void JNICALL Java_com_example_ffmpegtest_VideoUtils_decode
  (JNIEnv *, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
